baseURL = "https://***REMOVED***.nyc/"
languageCode = "en-us"            # idioma padr√£o
title = "Nonlinear"
publishDir = "docs"

[params]
author = "Nicholas Frota"

[outputs]
home = ["HTML", "RSS"]
section = ["HTML", "RSS"]
